name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe what should have happened..."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Describe what actually happened..."
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical - System unusable
        - High - Major functionality broken
        - Medium - Minor functionality affected
        - Low - Cosmetic issue
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Platform and version information
      placeholder: |
        - OS: [e.g., Android 13, iOS 16.1, Windows 11]
        - Device: [e.g., Pixel 7, iPhone 14, Desktop]
        - App Version: [e.g., 0.1.0]
        - Build: [e.g., debug, release]
  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: "Paste logs or drag and drop screenshots here..."