name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: "Describe the feature..."
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "This feature would solve the problem of..."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "The feature should work by..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "Alternative approaches could include..."
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical - Blocks major functionality
        - High - Important for user experience
        - Medium - Nice to have
        - Low - Future consideration
      default: 2
  - type: checkboxes
    id: affected-platforms
    attributes:
      label: Affected Platforms
      description: Which platforms would this feature affect?
      options:
        - label: Android
        - label: iOS
        - label: Desktop
        - label: Backend/Blockchain
        - label: All platforms
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature
      placeholder: "Additional details, mockups, or links..."